export enum Role {
  // Administrative Roles
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  SUPPORT = 'SUPPORT',

  // Organization Roles
  ORGANIZATION_ADMIN = 'ORGANIZATION_ADMIN',
  DOCUMENT_MANAGER = 'DOCUMENT_MANAGER',
  VERIFIER = 'VERIFIER',
  REVIEWER = 'REVIEWER',
  MEMBER = 'MEMBER',
  VIEWER = 'VIEWER',
  AUDITOR = 'AUDITOR',
  TEMPORARY = 'TEMPORARY',

  // General User Role
  USER = 'USER',
}
