export enum DocumentType {
  // Academic Documents
  ACADEMIC_CERTIFICATE = 'ACADEMIC_CERTIFICATE',
  ACADEMIC_TRANSCRIPT = 'ACADEMIC_TRANSCRIPT',
  DEGREE_CERTIFICATE = 'DEGREE_CERTIFICATE',
  DIPLOMA = 'DIPLOMA',
  COURSE_CERTIFICATE = 'COURSE_CERTIFICATE',
  THESIS_DOCUMENT = 'THESIS_DOCUMENT',

  // Government Documents
  GOVERNMENT_ID = 'GOVERNMENT_ID',
  PASSPORT = 'PASSPORT',
  DRIVERS_LICENSE = 'DRIVERS_LICENSE',
  BIRTH_CERTIFICATE = 'BIRTH_CERTIFICATE',
  MARRIAGE_CERTIFICATE = 'MARRIAGE_CERTIFICATE',
  TAX_DOCUMENT = 'TAX_DOCUMENT',
  VISA_DOCUMENT = 'VISA_DOCUMENT',
  CITIZENSHIP_DOCUMENT = 'CITIZENSHIP_DOCUMENT',

  // Professional Documents
  PROFESSIONAL_LICENSE = 'PROFESSIONAL_LICENSE',
  CERTIFICATION = 'CERTIFICATION',
  WORK_PERMIT = 'WORK_PERMIT',
  EMPLOYMENT_CONTRACT = 'EMPLOYMENT_CONTRACT',
  REFERENCE_LETTER = 'REFERENCE_LETTER',
  EXPERIENCE_CERTIFICATE = 'EXPERIENCE_CERTIFICATE',

  // Corporate Documents
  CORPORATE_DOCUMENT = 'CORPORATE_DOCUMENT',
  BUSINESS_LICENSE = 'BUSINESS_LICENSE',
  INCORPORATION_CERTIFICATE = 'INCORPORATION_CERTIFICATE',
  SHAREHOLDER_AGREEMENT = 'SHAREHOLDER_AGREEMENT',
  ANNUAL_REPORT = 'ANNUAL_REPORT',
  BOARD_RESOLUTION = 'BOARD_RESOLUTION',

  // Legal Documents
  LEGAL_DOCUMENT = 'LEGAL_DOCUMENT',
  CONTRACT = 'CONTRACT',
  POWER_OF_ATTORNEY = 'POWER_OF_ATTORNEY',
  COURT_ORDER = 'COURT_ORDER',
  AFFIDAVIT = 'AFFIDAVIT',
  LEGAL_NOTICE = 'LEGAL_NOTICE',

  // Medical Documents
  MEDICAL_CERTIFICATE = 'MEDICAL_CERTIFICATE',
  HEALTH_RECORD = 'HEALTH_RECORD',
  VACCINATION_RECORD = 'VACCINATION_RECORD',
  INSURANCE_DOCUMENT = 'INSURANCE_DOCUMENT',

  // Financial Documents
  BANK_STATEMENT = 'BANK_STATEMENT',
  FINANCIAL_STATEMENT = 'FINANCIAL_STATEMENT',
  AUDIT_REPORT = 'AUDIT_REPORT',
  TAX_RETURN = 'TAX_RETURN',

  // Property Documents
  PROPERTY_DEED = 'PROPERTY_DEED',
  LEASE_AGREEMENT = 'LEASE_AGREEMENT',
  PROPERTY_TAX_DOCUMENT = 'PROPERTY_TAX_DOCUMENT',

  // Other
  OTHER = 'OTHER',
}
