services:
  db:
    image: postgres:17.2
    environment:
      POSTGRES_USER: certuser
      POSTGRES_PASSWORD: certpass
      POSTGRES_DB: cert-db
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U certuser']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USE_HTTPS: ${USE_HTTPS:-false}
    image: cert-api:latest
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: certuser
      DB_PASSWORD: certpass
      DB_NAME: cert-db
      PORT: 3000
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost:3000/health || exit 1']
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

networks:
  default:
    name: cert_network
    driver: bridge

volumes:
  postgres-data:
    driver: local
