export enum NotificationType {
  EMAIL = 'EMAIL',
  SMS = 'SMS',
  IN_APP = 'IN_APP',
  PUSH = 'PUSH',
}

export enum NotificationContentType {
  // User Account Notifications
  ACCOUNT_CREATED = 'ACCOUNT_CREATED',
  EMAIL_VERIFICATION = 'EMAIL_VERIFICATION',
  PASSWORD_RESET_REQUEST = 'PASSWORD_RESET_REQUEST',
  ACCOUNT_STATUS_CHANGE = 'ACCOUNT_STATUS_CHANGE',
  LOGIN_ATTEMPT = 'LOGIN_ATTEMPT',
  TWO_FACTOR_SETUP = 'TWO_FACTOR_SETUP',

  // Document-related Notifications
  DOCUMENT_UPLOADED = 'DOCUMENT_UPLOADED',
  DOCUMENT_SUBMITTED = 'DOCUMENT_SUBMITTED',
  DOCUMENT_STATUS_CHANGE = 'DOCUMENT_STATUS_CHANGE',
  DOCUMENT_EXPIRATION_WARNING = 'DOCUMENT_EXPIRATION_WARNING',
  DOCUMENT_REVISION_REQUEST = 'DOCUMENT_REVISION_REQUEST',
  DOCUMENT_COMMENT = 'DOCUMENT_COMMENT',

  // Verification Process Notifications
  VERIFICATION_REQUEST_RECEIVED = 'VERIFICATION_REQUEST_RECEIVED',
  VERIFICATION_IN_PROGRESS = 'VERIFICATION_IN_PROGRESS',
  VERIFICATION_COMPLETED = 'VERIFICATION_COMPLETED',
  ADDITIONAL_INFO_REQUESTED = 'ADDITIONAL_INFO_REQUESTED',

  // Organization-related Notifications
  ORGANIZATION_REGISTERED = 'ORGANIZATION_REGISTERED',
  ORGANIZATION_APPROVAL_STATUS = 'ORGANIZATION_APPROVAL_STATUS',
  NEW_MEMBER_ADDED = 'NEW_MEMBER_ADDED',
  ROLE_CHANGE = 'ROLE_CHANGE',
  ORGANIZATION_STATUS_CHANGE = 'ORGANIZATION_STATUS_CHANGE',

  // Admin Notifications
  NEW_USER_REGISTRATION = 'NEW_USER_REGISTRATION',
  NEW_ORGANIZATION_REGISTRATION = 'NEW_ORGANIZATION_REGISTRATION',
  SUSPICIOUS_ACTIVITY = 'SUSPICIOUS_ACTIVITY',
  SYSTEM_PERFORMANCE_ALERT = 'SYSTEM_PERFORMANCE_ALERT',
  BULK_OPERATION = 'BULK_OPERATION',

  // Collaboration Notifications
  SHARED_DOCUMENT_ACCESS = 'SHARED_DOCUMENT_ACCESS',
  TASK_ASSIGNMENT = 'TASK_ASSIGNMENT',

  // Deadline and Reminder Notifications
  DOCUMENT_EXPIRATION_REMINDER = 'DOCUMENT_EXPIRATION_REMINDER',
  PENDING_VERIFICATION_REMINDER = 'PENDING_VERIFICATION_REMINDER',
  MAINTENANCE_REMINDER = 'MAINTENANCE_REMINDER',

  // Blockchain-related Notifications
  TRANSACTION_CONFIRMATION = 'TRANSACTION_CONFIRMATION',
  SMART_CONTRACT_EVENT = 'SMART_CONTRACT_EVENT',

  // Subscription and Billing Notifications
  SUBSCRIPTION_RENEWAL_REMINDER = 'SUBSCRIPTION_RENEWAL_REMINDER',
  PAYMENT_CONFIRMATION = 'PAYMENT_CONFIRMATION',
  USAGE_LIMIT_WARNING = 'USAGE_LIMIT_WARNING',

  // System Update Notifications
  NEW_FEATURE_ANNOUNCEMENT = 'NEW_FEATURE_ANNOUNCEMENT',
  MAINTENANCE_SCHEDULE = 'MAINTENANCE_SCHEDULE',
  SERVICE_DISRUPTION = 'SERVICE_DISRUPTION',

  // Audit and Compliance Notifications
  UNUSUAL_ACCOUNT_ACTIVITY = 'UNUSUAL_ACCOUNT_ACTIVITY',
  POLICY_VIOLATION = 'POLICY_VIOLATION',
  COMPLIANCE_DEADLINE = 'COMPLIANCE_DEADLINE',

  // Multi-factor Authentication Notifications
  MFA_SETUP = 'MFA_SETUP',
  MFA_VERIFICATION_CODE = 'MFA_VERIFICATION_CODE',
  MFA_METHOD_CHANGE = 'MFA_METHOD_CHANGE',

  // Data Privacy and Security Notifications
  DATA_ACCESS_REQUEST = 'DATA_ACCESS_REQUEST',
  PRIVACY_POLICY_UPDATE = 'PRIVACY_POLICY_UPDATE',
  SECURITY_RECOMMENDATION = 'SECURITY_RECOMMENDATION',

  // Integration Notifications
  API_KEY_CHANGE = 'API_KEY_CHANGE',
  WEBHOOK_DELIVERY_FAILURE = 'WEBHOOK_DELIVERY_FAILURE',
  INTEGRATION_STATUS_CHANGE = 'INTEGRATION_STATUS_CHANGE',

  // User Preference Updates
  NOTIFICATION_SETTINGS_CHANGE = 'NOTIFICATION_SETTINGS_CHANGE',
  LANGUAGE_TIMEZONE_UPDATE = 'LANGUAGE_TIMEZONE_UPDATE',

  // Document Template Notifications
  NEW_TEMPLATE_AVAILABLE = 'NEW_TEMPLATE_AVAILABLE',
  TEMPLATE_UPDATE = 'TEMPLATE_UPDATE',

  // Batch Processing Notifications
  BULK_OPERATION_START = 'BULK_OPERATION_START',
  BULK_OPERATION_COMPLETE = 'BULK_OPERATION_COMPLETE',

  // Training and Onboarding Notifications
  NEW_USER_GUIDE = 'NEW_USER_GUIDE',
  TRAINING_SESSION_REMINDER = 'TRAINING_SESSION_REMINDER',
  FEATURE_WALKTHROUGH = 'FEATURE_WALKTHROUGH',
}
