export enum AuditAction {
  // Document related actions
  UPLOAD_DOCUMENT = 'UPLOAD_DOCUMENT',
  UPDATE_DOCUMENT = 'UPDATE_DOCUMENT',
  DELETE_DOCUMENT = 'DELETE_DOCUMENT',
  VERIFY_DOCUMENT = 'VERIFY_DOCUMENT',
  REVOKE_DOCUMENT = 'REVOKE_DOCUMENT',
  DOCUMENT_STATUS_CHANGED = 'DOCUMENT_STATUS_CHANGED',
  DOCUMENT_SUBMITTED_FOR_VERIFICATION = 'DOCUMENT_SUBMITTED_FOR_VERIFICATION',
  DOCUMENT_VERIFICATION_APPROVED = 'DOCUMENT_VERIFICATION_APPROVED',
  DOCUMENT_VERIFICATION_REJECTED = 'DOCUMENT_VERIFICATION_REJECTED',
  DOCUMENT_REVOCATION_REQUESTED = 'DOCUMENT_REVOCATION_REQUESTED',
  DOCUMENT_REVOKED = 'DOCUMENT_REVOKED',
  GRANT_DOCUMENT_ACCESS = 'GRANT_DOCUMENT_ACCESS',
  REVOKE_DOCUMENT_ACCESS = 'REVOKE_DOCUMENT_ACCESS',

  // User related actions
  CREATE_USER = 'CREATE_USER',
  UPDATE_USER = 'UPDATE_USER',
  DELETE_USER = 'DELETE_USER',
  ACTIVATE_USER = 'ACTIVATE_USER',
  DEACTIVATE_USER = 'DEACTIVATE_USER',

  // Super Admin actions for User management
  APPROVE_USER = 'APPROVE_USER',
  REJECT_USER = 'REJECT_USER',
  SUSPEND_USER = 'SUSPEND_USER',
  UNSUSPEND_USER = 'UNSUSPEND_USER',
  GRANT_ADMIN_ROLE = 'GRANT_ADMIN_ROLE',
  REVOKE_ADMIN_ROLE = 'REVOKE_ADMIN_ROLE',

  // Organization related actions
  CREATE_ORGANIZATION = 'CREATE_ORGANIZATION',
  UPDATE_ORGANIZATION = 'UPDATE_ORGANIZATION',
  DELETE_ORGANIZATION = 'DELETE_ORGANIZATION',

  // Super Admin actions for Organization management
  APPROVE_ORGANIZATION = 'APPROVE_ORGANIZATION',
  REJECT_ORGANIZATION = 'REJECT_ORGANIZATION',
  SUSPEND_ORGANIZATION = 'SUSPEND_ORGANIZATION',
  UNSUSPEND_ORGANIZATION = 'UNSUSPEND_ORGANIZATION',

  // Authentication related actions
  USER_LOGIN = 'USER_LOGIN',
  USER_LOGOUT = 'USER_LOGOUT',
  FAILED_LOGIN_ATTEMPT = 'FAILED_LOGIN_ATTEMPT',
  PASSWORD_RESET = 'PASSWORD_RESET',

  // Verification related actions
  INITIATE_VERIFICATION = 'INITIATE_VERIFICATION',
  COMPLETE_VERIFICATION = 'COMPLETE_VERIFICATION',
  REJECT_VERIFICATION = 'REJECT_VERIFICATION',

  // System related actions
  SYSTEM_ERROR = 'SYSTEM_ERROR',
  CONFIGURATION_CHANGE = 'CONFIGURATION_CHANGE',

  // Super Admin specific actions
  SUPER_ADMIN_LOGIN = 'SUPER_ADMIN_LOGIN',
  MODIFY_SYSTEM_SETTINGS = 'MODIFY_SYSTEM_SETTINGS',
  VIEW_AUDIT_LOGS = 'VIEW_AUDIT_LOGS',
  EXPORT_AUDIT_LOGS = 'EXPORT_AUDIT_LOGS',
}
